### ISSUE TITLE
Gui-Verbesserungsvorschlaege

### ISSUE THREAD

**Issue by arturbosch** [Grumnir/MakeAStory#31]
- Login sollte durch Eingabe von Enter auch moeglich sein (nicht nur Button klicken)
- Benutzerpasswort wird in Klartext uebertragen
- das Absenden von Eintraegen durch Button oder Enter verliert den Fokus auf TextArea
- Tabelle 'benutzer' existiert nicht, sondern 'spieler'
- README um MySQL installieren und User anlegen erweitern (fuer nicht IT-affine)
- Schriftgroesse aendern macht nichts?
- Anlegen einer Geschichte/Kapitel sollte zum neuen Tab springen

Ich freue mich auf die Chatfunktion!

**Comment by Grumnir** [comment]
Hallo Artur,
erstmal Danke für das Feedback, es freut mich das sich meine Umstellung auf gradle bezahlt gemacht hat und nun auch andere sich MAS ansehen können ;) Zu deinen Punkten

- Login sollte durch Eingabe von Enter auch moeglich sein (nicht nur Button klicken)
=> Sollte eigentlich schon so sein, ich kann nochmal nachsehen ob das irgendwie abhanden kam.
- Benutzerpasswort wird in Klartext uebertragen
=> Ja, gebe ich dir absolut recht das muss noch passieren. Ich werde das für den nächsten Release einbauen. Kennst du ein schlanke und einfach zu bedienende Bibliothek für Hashfunktionen wie z.B. SHA-1? Wenn du da schon was passendes im Kopf hast muss ich nich erst suchen.
- das Absenden von Eintraegen durch Button oder Enter verliert den Fokus auf TextArea
=> Das ist ein noch fehlendes Feature aus der alten Oberfläche, wird auch umgesetzt
- Tabelle 'benutzer' existiert nicht, sondern 'spieler'
=> Wird korrigiert danke für den Hinweis
- README um MySQL installieren und User anlegen erweitern (fuer nicht IT-affine)
=> User anlegen soll theoretisch zum nächsten Release durch MAS gemacht werden können, dann also auch einfacher und benutzerfreundlicher werden. Dabei werde ich dann sicher auch die README anpassen
- Schriftgroesse aendern macht nichts
=> Auch das ging bei mir, vielleicht kann ich da noch einen Weg finden das anders zu machen als bisher
- Anlegen einer Geschichte/Kapitel sollte zum neuen Tab springen
=> Guter Plan, wird gleich vermerkt

Ich werde die Vorschläge in weiteres Issues verwandeln und entsprechend dem Zielrelease dann zuweisen. Wann der dann kommt hängt aber stark von meiner Zeit für MAS ab ;)

Viele Grüße,
Grumnir

**Comment by Grumnir** [comment]
Ich habe inzwischen das Ändern der Schriftgröße geändert. Vorher wurde dies durch setzen einer CSS Eigenschaft gemacht. Da ich nun Textflow benutze, wo jeder Eintrag ein eigener Text ist, habe ich in diesem Zuge auf eine programmatische Änderung des Fonts gewechselt. Kannst du bei Zeiten nachprüfen, ob die Schriftgröße sich bei dir nun auch ändert wie geplant?

**Comment by Grumnir** [comment]
Alle Vorschläge flossen in v1.2 ein.
