### ISSUE TITLE
Passwort hashen

### ISSUE THREAD

**Issue by Grumnir** [Grumnir/MakeAStory#32]
Derzeit wird das Passwort nicht verschlüsselt. Das soll sich ändern

**Comment by arturbosch** [comment]
Diese Klasse habe ich mal geschrieben gehabt, die mit SHA-256 hashen kann:

```
public final class Hash {

	private static final MessageDigest digest;

	static {
		try {
			digest = MessageDigest.getInstance("SHA-256");
		} catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(e);
		}
	}

	public static String sha256(String password) {
		return DatatypeConverter.printHexBinary(digest.digest(password.getBytes()));
	}
}

```

**Comment by arturbosch** [comment]
Doch Vorsicht! Mit java9 ist java.xml.bind nicht mehr im `java.base` oder `java.se' module sondern im `java.se.ee' bzw `java.xml.bind` module drinne. Dann muss per flag `--add-module` `java.xml.bind` hinzugefuegt werden.

Waere jedoch der einfachste weg ohne Zusatzlibs.
